=== Rubix233/DAM/Acceso a Datos/RefuerzoXML/ExtraXML/xml-resources/jaxb/PeliculasBinding/XMLSchemaAvanzados05_videoclub.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- Versión sin definición de tipos de datos -->

<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="facturas" elementFormDefault="unqualified"
	    xmlns:fact="facturas">	

<!-- ====== ELEMENTO facturas ====== -->
	<element name="facturas">
      		<complexType>
         		<sequence>
				<element ref="fact:factura" minOccurs="0" maxOccurs="unbounded" />
         		</sequence>
      		</complexType>
	</element>	
 <!-- ====== ELEMENTO factura ====== -->  	
	<element name="factura">
      		<complexType>
         		<sequence>
            			<element ref="fact:datos_cliente" minOccurs="1" maxOccurs="1" />
				<element ref="fact:datos_factura" minOccurs="1" maxOccurs="1" />
			</sequence>
		</complexType>
	</element>
<!-- ====== ELEMENTO datos_cliente ====== -->
	<element name="datos_cliente">
		<complexType>
         	<sequence>
            	<element ref="fact:nombre" minOccurs="1" maxOccurs="1" />
				<element ref="fact:apellido" minOccurs="2" maxOccurs="2" />
				<element ref="fact:dni" minOccurs="1" maxOccurs="1" />
				<element ref="fact:tfno" minOccurs="1" maxOccurs="1" />
			</sequence>
			<attribute name="ident" type="string" use="required" />
		</complexType>
	</element>
<!-- ====== ELEMENTO nombre ====== -->
	<element name="nombre" type="string" />
<!-- ====== ELEMENTO apellido ====== -->
	<element name="apellido" type="string" />
<!-- ====== ELEMENTO dni ====== -->
	<element name="dni">
		<simpleType>
			<restriction base="string">
				<pattern value="[0-9]{8}[A-Z]" />
			</restriction>
		</simpleType>
	</element>
<!-- ====== ELEMENTO tfno ====== -->
	<element name="tfno">
		<simpleType>
			<restriction base="string">
				<pattern value="[0-9]{9}" />
			</restriction>
		</simpleType>
	</element>
<!-- ====== ELEMENTO datos_factura ====== -->
	<element name="datos_factura">
		<complexType>
         	<sequence>
            	<element ref="fact:resguardo" minOccurs="1" maxOccurs="1" />
					<choice>
						<element ref="fact:alquileres" minOccurs="1" maxOccurs="1" />
						<element ref="fact:compras" minOccurs="1" maxOccurs="1" />
						<element name="alquileres_compras">
                            <complexType>
                                <sequence>
									<element ref="fact:alquileres" minOccurs="1" maxOccurs="1" />
									<element ref="fact:compras" minOccurs="1" maxOccurs="1" />
								</sequence>
                            </complexType>
                        </element>
					</choice>
			</sequence>
		</complexType>
	</element>
	
<!-- ====== ELEMENTO resguardo ====== -->
	<element name="resguardo">
		<complexType>
			<sequence>
				<element ref="fact:forma_pago" minOccurs="1" maxOccurs="1" />
				<element ref="fact:importe_total" minOccurs="1" maxOccurs="1" />
			</sequence>
		</complexType>
	</element>
<!-- ====== ELEMENTO forma_pago ====== -->
	<element name="forma_pago" type="string" />
<!-- ====== ELEMENTO importe_total ====== -->
	<element name="importe_total" type="float" />
<!-- ====== ELEMENTO alquileres ====== -->
	<element name="alquileres">
		<complexType>
			<sequence>
				<element ref="fact:fecha" minOccurs="1" maxOccurs="1" />
				<element ref="fact:peliculas" minOccurs="1" maxOccurs="1" />
			</sequence>
		</complexType>
	</element>
<!-- ====== ELEMENTO fecha ====== -->
	<element name="fecha" type="date" />
<!-- ====== ELEMENTO peliculas ====== -->
	<element name="peliculas">
		<complexType>
			<sequence>
				<element ref="fact:pelicula" minOccurs="1" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
<!-- ====== ELEMENTO pelicula ====== -->
	<element name="pelicula">
		<complexType>
			<sequence>
				<element ref="fact:titulo" minOccurs="1" maxOccurs="1" />
				<element ref="fact:genero" minOccurs="1" maxOccurs="1" />
				<element ref="fact:duracion" minOccurs="1" maxOccurs="1" />
				<element ref="fact:actores" minOccurs="1" maxOccurs="1" />
			</sequence>
			<attribute name="id_pelicula" type="string" use="required" />
			<attribute name="valoracion" type="string" />
		</complexType>
	</element>
<!-- ====== ELEMENTO titulo ====== -->
	<element name="titulo" type="string" />
<!-- ====== ELEMENTO genero ====== -->
	<element name="genero" type="string" />
<!-- ====== ELEMENTO duracion ====== -->
	<element name="duracion" type="positiveInteger" />
<!-- ====== ELEMENTO actores ====== -->
	<element name="actores">
		<complexType>
			<sequence>
				<element ref="fact:actor" minOccurs="3" maxOccurs="3" />
			</sequence>
		</complexType>
	</element>
<!-- ====== ELEMENTO actor ====== -->
	<element name="actor">
		<complexType>
         		<sequence>
            			<element ref="fact:nombre" minOccurs="1" maxOccurs="1" />
				<element ref="fact:apellido" minOccurs="2" maxOccurs="2" />
			</sequence>
		</complexType>
	</element>
<!-- ====== ELEMENTO compras ====== -->		
	<element name="compras">
		<complexType>
			<choice>
				<element ref="fact:dvds" minOccurs="1" maxOccurs="1" />
				<element ref="fact:cintas" minOccurs="1" maxOccurs="1" />
				<element name="dvds_cintas">
                    <complexType>
						<sequence>
							<element ref="fact:dvds" minOccurs="1" maxOccurs="1" />
							<element ref="fact:cintas" minOccurs="1" maxOccurs="1" />
						</sequence>
                    </complexType>
                </element>
			</choice>
		</complexType>
	</element>
<!-- ====== ELEMENTO dvds ====== -->
	<element name="dvds">
		<complexType>
			<sequence>
				<element ref="fact:dvd" minOccurs="1" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
<!-- ====== ELEMENTO dvd ====== -->
	<element name="dvd">
		<complexType>
			<sequence>
				<element ref="fact:extras" minOccurs="0" maxOccurs="1" />
				<element ref="fact:titulo" minOccurs="1" maxOccurs="1" />
				<element ref="fact:fecha_salida_mercado" minOccurs="1" maxOccurs="1" />
			</sequence>
		</complexType>
	</element>
<!-- ====== ELEMENTO extras ====== -->
	<element name="extras">
		<complexType />
	</element>
<!-- ====== ELEMENTO fecha_salida_mercado ====== -->
	<element name="fecha_salida_mercado" type="date" />
<!-- ====== ELEMENTO cintas ====== -->
	<element name="cintas">
		<complexType>
			<sequence>
				<element ref="fact:cinta" minOccurs="1" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
<!-- ====== ELEMENTO cinta ====== -->
	<element name="cinta">
		<complexType>
			<sequence>
				<element ref="fact:titulo" minOccurs="1" maxOccurs="1" />
				<element ref="fact:formato" minOccurs="1" maxOccurs="1" />
				<element ref="fact:rebobinado" minOccurs="0" maxOccurs="1" />
			</sequence>
		</complexType>
	</element>
<!-- ====== ELEMENTO formato ====== -->
	<element name="formato" type="string" />
<!-- ====== ELEMENTO rebobinado ====== -->
	<element name="rebobinado">
		<complexType />
	</element>
</schema>

=== Rubix233/DAM/Acceso a Datos/RefuerzoXML/ExtraXML/Archivos/XMLSchemaAvanzados05_videoclub.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:facturas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="facturas XMLSchemaAvanzados05_videoclub.xsd"
               xmlns:ns1="facturas">
    
    <ns1:factura>
        <ns1:datos_cliente ident="abcd">
            <ns1:nombre>Juan</ns1:nombre>
            <ns1:apellido>López</ns1:apellido>
            <ns1:apellido>Jiménez</ns1:apellido>
            <ns1:dni>11111111N</ns1:dni>
            <ns1:tfno>123456789</ns1:tfno>
        </ns1:datos_cliente>
        <ns1:datos_factura>
            <ns1:resguardo>
                <ns1:forma_pago>Efectivo</ns1:forma_pago>
                <ns1:importe_total>10.50</ns1:importe_total>
            </ns1:resguardo>
            <ns1:alquileres>
                <ns1:fecha>2026-02-10</ns1:fecha>
                <ns1:peliculas>
                    <ns1:pelicula id_pelicula="PELI01" valoracion="buena">
                        <ns1:titulo>El retorno del Jedi</ns1:titulo>
                        <ns1:genero>Ciencia Ficción</ns1:genero>
                        <ns1:duracion>125</ns1:duracion>
                        <ns1:actores>
                            <ns1:actor>
								<ns1:nombre>Mark</ns1:nombre>
								<ns1:apellido>Hamill</ns1:apellido>
								<ns1:apellido>S.</ns1:apellido>
							</ns1:actor>
                            <ns1:actor>
								<ns1:nombre>Harrison</ns1:nombre>
								<ns1:apellido>Ford</ns1:apellido>
								<ns1:apellido>T.</ns1:apellido>
							</ns1:actor>
                            <ns1:actor>
								<ns1:nombre>Carrie</ns1:nombre>
								<ns1:apellido>Fisher</ns1:apellido>
								<ns1:apellido>L.</ns1:apellido>
							</ns1:actor>
                        </ns1:actores>
                    </ns1:pelicula>
                </ns1:peliculas>
            </ns1:alquileres>
        </ns1:datos_factura>
    </ns1:factura>

    <ns1:factura>
        <ns1:datos_cliente ident="efgh">
            <ns1:nombre>Maria</ns1:nombre>
            <ns1:apellido>Garcia</ns1:apellido>
            <ns1:apellido>Sanz</ns1:apellido>
            <ns1:dni>22222222A</ns1:dni>
            <ns1:tfno>987654321</ns1:tfno>
        </ns1:datos_cliente>
        <ns1:datos_factura>
            <ns1:resguardo>
                <ns1:forma_pago>Tarjeta</ns1:forma_pago>
                <ns1:importe_total>25.00</ns1:importe_total>
            </ns1:resguardo>
            <ns1:alquileres>
                <ns1:fecha>2026-02-11</ns1:fecha>
                <ns1:peliculas>
                    <ns1:pelicula id_pelicula="PELI01" valoracion="buena">
                        <ns1:titulo>El retorno del Jedi</ns1:titulo>
                        <ns1:genero>Ciencia Ficción</ns1:genero>
                        <ns1:duracion>125</ns1:duracion>
                        <ns1:actores>
                            <ns1:actor>
								<ns1:nombre>A1</ns1:nombre>
								<ns1:apellido>Ap1</ns1:apellido>
								<ns1:apellido>Ap2</ns1:apellido>
							</ns1:actor>
                            <ns1:actor>
								<ns1:nombre>A2</ns1:nombre>
								<ns1:apellido>Ap1</ns1:apellido>
								<ns1:apellido>Ap2</ns1:apellido>
							</ns1:actor>
                            <ns1:actor>
								<ns1:nombre>A3</ns1:nombre>
								<ns1:apellido>Ap1</ns1:apellido>
								<ns1:apellido>Ap2</ns1:apellido>
							</ns1:actor>
                        </ns1:actores>
                    </ns1:pelicula>
                    <ns1:pelicula id_pelicula="PELI02" valoracion="excelente">
                        <ns1:titulo>Inception</ns1:titulo>
                        <ns1:genero>Thriller</ns1:genero>
                        <ns1:duracion>148</ns1:duracion>
                        <ns1:actores>
                            <ns1:actor>
								<ns1:nombre>Leonardo</ns1:nombre>
								<ns1:apellido>Di</ns1:apellido>
								<ns1:apellido>Caprio</ns1:apellido>
							</ns1:actor>
                            <ns1:actor>
								<ns1:nombre>Tom</ns1:nombre>
								<ns1:apellido>Hardy</ns1:apellido>
								<ns1:apellido>E.</ns1:apellido>
							</ns1:actor>
                            <ns1:actor>
								<ns1:nombre>Cillian</ns1:nombre>
								<ns1:apellido>Murphy</ns1:apellido>
								<ns1:apellido>M.</ns1:apellido>
							</ns1:actor>
                        </ns1:actores>
                    </ns1:pelicula>
                </ns1:peliculas>
            </ns1:alquileres>
        </ns1:datos_factura>
    </ns1:factura>

    <ns1:factura>
        <ns1:datos_cliente ident="ijkl">
            <ns1:nombre>Carlos</ns1:nombre>
            <ns1:apellido>Ruiz</ns1:apellido>
            <ns1:apellido>Gomez</ns1:apellido>
            <ns1:dni>33333333B</ns1:dni>
            <ns1:tfno>666555444</ns1:tfno>
        </ns1:datos_cliente>
        <ns1:datos_factura>
            <ns1:resguardo>
                <ns1:forma_pago>Efectivo</ns1:forma_pago>
                <ns1:importe_total>50.00</ns1:importe_total>
            </ns1:resguardo>
            <ns1:alquileres_compras>
                <ns1:alquileres>
                    <ns1:fecha>2026-02-12</ns1:fecha>
                    <ns1:peliculas>
                        <ns1:pelicula id_pelicula="PELI02" valoracion="media">
                            <ns1:titulo>Inception</ns1:titulo>
                            <ns1:genero>Thriller</ns1:genero>
                            <ns1:duracion>148</ns1:duracion>
                            <ns1:actores>
                                <ns1:actor>
									<ns1:nombre>A1</ns1:nombre>
									<ns1:apellido>Ap1</ns1:apellido>
									<ns1:apellido>Ap2</ns1:apellido>
								</ns1:actor>
                                <ns1:actor>
									<ns1:nombre>A2</ns1:nombre>
									<ns1:apellido>Ap1</ns1:apellido>
									<ns1:apellido>Ap2</ns1:apellido>
								</ns1:actor>
                                <ns1:actor>
									<ns1:nombre>A3</ns1:nombre>
									<ns1:apellido>Ap1</ns1:apellido>
									<ns1:apellido>Ap2</ns1:apellido>
								</ns1:actor>
                            </ns1:actores>
                        </ns1:pelicula>
                    </ns1:peliculas>
                </ns1:alquileres>
                <ns1:compras>
                    <ns1:dvds>
                        <ns1:dvd>
                            <ns1:titulo>The Matrix</ns1:titulo>
                            <ns1:fecha_salida_mercado>1999-03-31</ns1:fecha_salida_mercado>
                        </ns1:dvd>
                    </ns1:dvds>
                </ns1:compras>
            </ns1:alquileres_compras>
        </ns1:datos_factura>
    </ns1:factura>
</ns1:facturas>

=== Rubix233/DAM/Acceso a Datos/RefuerzoXML/ExtraXML/XMLSchemaAvanzados05_videoclub.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:facturas  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="facturas XMLSchemaAvanzados05_videoclub.xsd"
			   xmlns:ns1="facturas">
       <ns1:factura>
            <ns1:datos_cliente ident="abcd">
                <ns1:nombre>Juan</ns1:nombre>
                <ns1:apellido>López</ns1:apellido>
                <ns1:apellido>Jiménez</ns1:apellido>
                <ns1:dni>11111111N</ns1:dni>
                <ns1:tfno>123456789</ns1:tfno>
            </ns1:datos_cliente>
            <ns1:datos_factura>
                <ns1:resguardo>
                    <ns1:forma_pago>
                        Efectivo
                    </ns1:forma_pago>
                    <ns1:importe_total>
                        1256325.23
                    </ns1:importe_total>
                </ns1:resguardo>
                <ns1:alquileres>
                    <ns1:fecha>2010-12-25</ns1:fecha>
                    <ns1:peliculas>
                        <ns1:pelicula id_pelicula="ABC" valoracion="buena">
                            <ns1:titulo>El retorno del Jedi</ns1:titulo>
                            <ns1:genero>Espacio</ns1:genero>
                            <ns1:duracion>125</ns1:duracion>
                            <ns1:actores>
                                <ns1:actor>
                                    <ns1:nombre>Juan</ns1:nombre>
                                    <ns1:apellido>Pardo</ns1:apellido>
                                    <ns1:apellido>López</ns1:apellido>
                                </ns1:actor>
                                <ns1:actor>
                                    <ns1:nombre>Manuel</ns1:nombre>
                                    <ns1:apellido>Bandera</ns1:apellido>
                                    <ns1:apellido>Garrido</ns1:apellido>
                                </ns1:actor>
                                <ns1:actor>
                                    <ns1:nombre>Luis</ns1:nombre>
                                    <ns1:apellido>González</ns1:apellido>
                                    <ns1:apellido>Romero</ns1:apellido>
                                </ns1:actor>
                            </ns1:actores>
                        </ns1:pelicula>
                    </ns1:peliculas>
                </ns1:alquileres>
            </ns1:datos_factura>
       </ns1:factura>
</ns1:facturas>
