=== Rubix233/DAM/Acceso a Datos/ExamenXML/JanAndy/xml-resources/jaxb/CompeticionesBinding/competicionesEsquema.xsd
<?xml version="1.0"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<xsd:schema version="1.0"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
            elementFormDefault="qualified">
    <xsd:element name="competiciones">
        <xsd:complexType>
            <xsd:sequence>  
                <xsd:element name="competicion" type="TipoCompeticion" maxOccurs="50" minOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>           
  <xsd:complexType name="TipoParticipante">
	<xsd:sequence>
		<xsd:element name="nombre">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:minLength value="1"></xsd:minLength>
					<xsd:maxLength value="15"></xsd:maxLength>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:element>
		<xsd:element name="apellidos">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:minLength value="1"></xsd:minLength>
					<xsd:maxLength value="30"></xsd:maxLength>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:element>
		<xsd:element name="direccion" type="TipoDireccion"/>
	 </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="TipoDireccion">
     <xsd:sequence>
      <xsd:element name="calle"  type="xsd:string"/>
      <xsd:element name="numero">
		<xsd:simpleType>
			<xsd:restriction base="xsd:integer">
				<xsd:pattern value="[0-9]{3}"/>
			</xsd:restriction>
		</xsd:simpleType>
	  </xsd:element>	
      <xsd:element name="poblacion">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:minLength value="1"></xsd:minLength>
				<xsd:maxLength value="25"></xsd:maxLength>
			</xsd:restriction>
		</xsd:simpleType>
	  </xsd:element>
      <xsd:element name="provincia">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:minLength value="1"></xsd:minLength>
				<xsd:maxLength value="20"></xsd:maxLength>
			</xsd:restriction>
		</xsd:simpleType>
	  </xsd:element>
      <xsd:element name="codigoPostal">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[0-9]{5}"/>
			</xsd:restriction>
		</xsd:simpleType>
	  </xsd:element>	  
    </xsd:sequence>
  </xsd:complexType>

  <xsd:simpleType name="TipoCodigo">
    <xsd:restriction base="xsd:integer">
        <xsd:minInclusive value="1"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="TipoPruebas">
    <xsd:sequence>
      <xsd:element name="prueba" minOccurs="1" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="nombrePrueba">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:minLength value="1"></xsd:minLength>
			<xsd:maxLength value="15"></xsd:maxLength>
                    </xsd:restriction>			
                </xsd:simpleType>    
            </xsd:element>
            <xsd:element name="puntuacion">
              <xsd:simpleType>
                <xsd:restriction base="xsd:double">
                  <xsd:minInclusive value="1"/>
                  <xsd:maxExclusive value="10"/>
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:element>
            <xsd:element name="peso">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:minInclusive value="1"/>
                        <xsd:maxExclusive value="100"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
			<xsd:element name="tipo">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="habilidad"/>
						<xsd:enumeration value="tÃ©cnica"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>	
	 </xsd:sequence>
        <xsd:attribute name="numero" type="TipoCodigo"/>
       </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="TipoCompeticion">
    <xsd:sequence>
      <xsd:element name="participante" type="TipoParticipante"/>
      <xsd:element name="fecha" type="xsd:date"/>
      <xsd:element name="pruebas"  type="TipoPruebas"/>
    </xsd:sequence>
   </xsd:complexType>
</xsd:schema>

=== Rubix233/DAM/Acceso a Datos/ExamenXML/JanAndy/ContenidoProporcionado/competiciones.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<competiciones
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='competicionesEsquema.xsd'>
    <competicion>
        <participante>
            <nombre>Manuel</nombre>
            <apellidos>González Díaz</apellidos>
            <direccion>
                <calle>Andalucía</calle>
                <numero>023</numero>
                <poblacion>Medina del campo</poblacion>
                <provincia>Cádiz</provincia>
                <codigoPostal>40876</codigoPostal>
            </direccion>
        </participante>
        <fecha>2020-01-23</fecha>
        <pruebas>
            <prueba numero="5">
                <nombrePrueba>Oficial</nombrePrueba>
                <puntuacion>5.7</puntuacion>
                <peso>50</peso>
				<tipo>técnica</tipo>
            </prueba>
            <prueba numero="3">
                <nombrePrueba>Autonómica</nombrePrueba>
                <puntuacion>8</puntuacion>
                <peso>20</peso>
				<tipo>técnica</tipo>				
            </prueba>
            <prueba numero="1">
                <nombrePrueba>Entrenamiento</nombrePrueba>
                <puntuacion>7.8</puntuacion>
                <peso>10</peso>
				<tipo>habilidad</tipo>				
            </prueba>            
        </pruebas>
    </competicion>
    <competicion>
        <participante>
            <nombre>Saray</nombre>
            <apellidos>Alavez Mora</apellidos>
            <direccion>
                <calle>Aurora Boreal</calle>
                <numero>012</numero>
                <poblacion>Mairena del Aljarafe</poblacion>
                <provincia>Sevilla</provincia>
                <codigoPostal>41927</codigoPostal>
            </direccion>
        </participante>
        <fecha>2020-01-10</fecha>
        <pruebas>
            <prueba numero="2">
                <nombrePrueba>Local</nombrePrueba>
                <puntuacion>8.6</puntuacion>
                <peso>15</peso>
				<tipo>habilidad</tipo>
            </prueba>
            <prueba numero="3">
                <nombrePrueba>Autonómica</nombrePrueba>
                <puntuacion>4.5</puntuacion>
                <peso>20</peso>
				<tipo>técnica</tipo>				
            </prueba>
            <prueba numero="1">
                <nombrePrueba>Entrenamiento</nombrePrueba>
                <puntuacion>6.75</puntuacion>
                <peso>10</peso>
				<tipo>habilidad</tipo>				
            </prueba>            
        </pruebas>
    </competicion>    
    <competicion>
        <participante>
            <nombre>Javier</nombre>
            <apellidos>Soto del Real</apellidos>
            <direccion>
                <calle>Nueva</calle>
                <numero>032</numero>
                <poblacion>San Juan del Aznalfarache</poblacion>
                <provincia>Sevilla</provincia>
                <codigoPostal>41926</codigoPostal>
            </direccion>
        </participante>
        <fecha>2020-02-02</fecha>
        <pruebas>
            <prueba numero="4">
                <nombrePrueba>Benéfico</nombrePrueba>
                <puntuacion>6.4</puntuacion>
                <peso>40</peso>
				<tipo>técnica</tipo>				
            </prueba>
            <prueba numero="2">
                <nombrePrueba>Local</nombrePrueba>
                <puntuacion>9.2</puntuacion>
                <peso>15</peso>
				<tipo>habilidad</tipo>			
            </prueba>
        </pruebas>
    </competicion>   
    <competicion>
        <participante>
            <nombre>Nuria</nombre>
            <apellidos>Fuentes Pérez</apellidos>
            <direccion>
                <calle>Isabela</calle>
                <numero>002</numero>
                <poblacion>Sevilla</poblacion>
                <provincia>Sevilla</provincia>
                <codigoPostal>41013</codigoPostal>
            </direccion>
        </participante>
        <fecha>2020-02-02</fecha>
        <pruebas>
            <prueba numero="1">
                <nombrePrueba>Entrenamiento</nombrePrueba>
                <puntuacion>7.75</puntuacion>
                <peso>10</peso>
				<tipo>habilidad</tipo>					
            </prueba>              
            <prueba numero="4">
                <nombrePrueba>Benéfico</nombrePrueba>
                <puntuacion>8.4</puntuacion>
                <peso>40</peso>
				<tipo>técnica</tipo>				
            </prueba>
            <prueba numero="5">
                 <nombrePrueba>Oficial</nombrePrueba>
                <puntuacion>8.25</puntuacion>
                <peso>50</peso>
				<tipo>técnica</tipo>		
            </prueba>
        </pruebas>
    </competicion>            
</competiciones>
